[package]
name = "matey"
version = "0.1.0"
authors = ["Eshan Singh <eshansingh@gmail.com>", "Jeff Zhang <zhang.jeffreyd@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6"
snafu = "0.6"